# ----- Codes Start from here -----

from random import randint # This is the built-in module of python... that I used in this game...

blocks = ["-----------------------", # This one is the main intro part... I used it as a list for a btter look
"----- Battle Ship -----", 
"-----------------------",]

for intro in blocks:
    print(intro+"\n") # Here I used "\n" to keep space in the every part of the block list... 
                      # This will make a better look for the battle-ship intro...

board = [] # This is the list where the whole game will be hold ...

for i in range(5):
    board.append(["O"]*5) # This a "for-loop" by which I made the main structure of the board of battle-ship
                          # This is quite easy to handle a big part of list...

def print_board(board_in):# This one is the main function of the board... which will print the board everytime you want...
    for row in board_in:
        print(" ".join(row))
print("***Battle Board***\n")
print_board(board)

ship_row = randint(0, len(board)-1)
ship_col = randint(0, len(board[0])-1)
# These are the row and column of the board of the ship...

turn = 0 # This is the turn variable which will increament everytime when you takes a new turn...

while True:# By using while loop... This game will keep continue until you close it or you make a right guess...
    turn += 1 # This is the part that will increament the turn part...
    print("\nTurn", turn)
    user_row = input("Guess the Ship Row number in '0' to '4' \n You may write 'q' or 'quit' to quit the game immediately... :-> ")
    user_col = input("Guess the Ship Column number in '0' to '4' \n You may write 'q' or 'quit' to quit the game immediately... :-> ")
    # This is the user guess part... 

    if user_row.lower() == "q" or user_col.lower() == "q" or user_row.lower() == "quit" or user_col.lower() == "quit":
        print("\nGame Over...\n")
        break # This will break the code when someone type "q" or "Quit" or "quit"
    
    elif user_row.isdigit() == False or user_col.isdigit() == False: # This will check if the given value is a digit or not... if not... then it'll execute this...
        print("\nPlease enter a number...\n")
        turn -= 1 # For stop increament the turning value... this will help until the user gives an integer value
        continue # This is the part when.... someone try something else without an integer...
                 # It'll automatically continue the loop untill the give an integer value...
                 
    elif int(user_row) >= 5 or int(user_col) >= 5: # This is for when someone input something more than or equal 5 ... this statement will execute...
        print("\nOpps! You've missed the ship...\n")
        print_board(board)
        
    elif board[int(user_row)][int(user_col)] == "X": # This is for when someone accidently attack on the same place
                                                     #that he have tried before and missed...
                                                     # This will be execute then...
        print("\nYou've already attacked there once...\n")
        turn -= 1 # For stop increament the turning value...
        print_board(board)
        
    elif int(user_row) != ship_row or int(user_col) != ship_col: # This is for when someone missed the target this will set a 'X' in that row-column...
        print("\nYou've missed the target...\n")
        board[int(user_row)][int(user_col)] = "X" # I may use this int(user_row) and int(user_col) in a variable and set that here...
                                                  # But in while loop that could check first and sometime that gives an error of module or something else...
                                                  #So it's better to use int(user_row) int(user_col) here...
        print_board(board)
        
    elif int(user_row) == ship_row and int(user_col) == ship_col: #This is for when someone guess right target...
        print("\nGood! You won...\n")
        board[int(user_row)][int(user_col)] = "√" # This is the main part where...
                                                  # It'll break the loop when you'll guess right...
                                                  # and set '√' in the row-column... 
        print_board(board)
        print("\nYou've made it in", turn, "turns.\nand...")# This will tell you how much turn you've taken for right guess...
        # Let's create something that will give a grade to the user for guess turns...
        if turn <= 5:
            print("You've got 'A' grade for right guess...in",turn,"turns...")
        elif turn <= 10:
            print("You've got 'B' grade for right guess...in",turn,"turns...")
        elif turn <= 15:
            print("You've got 'C' grade for right guess...in",turn,"turns...")
        elif turn <= 20:
            print("You've got 'D' grade for right guess...in",turn,"turns...")
        elif turn <= 25:
            print("You've got 'E' grade for right guess...in",turn,"turns...")
        # It's won't effect your programm if you don't give an else statement...
        # This will give a grade of IQ according to the user guessing turns...

        break # After that this loop will break...

input("\nPress 'Enter' to quit...") # This is mainly for hold the CMD to see the results..
quit()# and also by pressing 'Enter' ... this will quit the game...



